title: "Bozart Botanics"
description: "Cannabis Wissenschaft • Grow Guides • DWC • Terpene • Seed-to-Harvest"

url: "https://bozart-army.github.io"
baseurl: "/bozart-botanics"

markdown: kramdown

# (Optional, aber harmless)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
